# golangci-lint configuration for tvarr
# https://golangci-lint.run/usage/configuration/
# Compatible with golangci-lint v2.x

version: "2"

# Linters configuration
linters:
  # Default set: 'standard' (enabled by default), 'all', or 'none'
  default: none

  # Enable specific linters
  enable:
    # Bugs and correctness
    - errcheck        # Check for unchecked errors
    - govet           # Reports suspicious constructs
    - ineffassign     # Detect ineffectual assignments
    - staticcheck     # Go static analysis (includes gosimple in v2)
    - unused          # Check for unused constants, variables, functions and types

    # Style and formatting
    - misspell        # Find commonly misspelled English words
    - whitespace      # Check for trailing whitespace



    # Best practices
    - errname         # Check error naming conventions
    - goprintffuncname # Check printf-like functions are named with f at the end
    - nolintlint      # Ensure nolint directives are properly used

    # Security
    - gosec           # Security problems

    # Modern Go features
    # gomoddirectives disabled - we use intentional replace for forked dependencies
    # - gomoddirectives # Manage replace, retract directives in go.mod
    - gomodguard      # Check for blocked dependencies

    # Testing
    - tparallel       # Detects inappropriate usage of t.Parallel()

  # Linters settings
  settings:
    # Error checking
    errcheck:
      check-type-assertions: false  # Type assertions with ok pattern are acceptable
      check-blank: false  # Allow blank identifier for intentionally ignored errors
      exclude-functions:
        - (io.Closer).Close
        - (*database/sql.Rows).Close
        - (*github.com/spf13/cobra.Command).MarkFlagRequired
        - io.Copy
        - (io.Writer).Write
        - (*bytes.Buffer).Write
        - (*bytes.Buffer).WriteString
        - (*strings.Builder).Write
        - (*strings.Builder).WriteString
        - fmt.Fprintf
        - fmt.Fprint
        - fmt.Fprintln
        - fmt.Sscanf
        - (net/http.ResponseWriter).Write
        - (*encoding/xml.Decoder).Skip
        - xml.EscapeText




    # Security
    gosec:
      excludes:
        - G104  # Audit errors not checked (covered by errcheck)
        - G115  # Integer overflow in conversions (acceptable for process stats parsing)
        - G117  # Exported field name matches secret pattern - false positive for API/config structs (Password, AuthToken fields are legitimate)
        - G204  # Subprocess launched with variable (FFmpeg wrapper intentionally uses dynamic commands)
        - G301  # Directory permissions (acceptable for data directories)
        - G302  # File permissions (acceptable for generated files)
        - G306  # WriteFile permissions (acceptable for non-sensitive files)
        - G307  # Deprecated - defer in loop
        - G404  # Use of weak random number generator (acceptable for non-crypto uses)
        - G703  # Path traversal via taint analysis - false positive: paths are validated before use
        - G704  # SSRF via taint analysis - false positive: URLs come from user-configured IPTV sources (by design)
        - G705  # XSS via taint analysis - false positive: we serve binary media streams and JSON, not HTML
        - G706  # Log injection via taint analysis - false positive: slog structured logging is not injectable
      config:
        global:
          audit: true



    # Static check
    staticcheck:
      checks:
        - all
        - -SA1019  # Allow deprecated packages (we'll handle these explicitly)
        - -ST1003  # Naming conventions for initialisms (API, ID, etc.) - too noisy
        - -QF1003  # Tagged switch suggestions - style preference
        - -QF1008  # Embedded field selector - style preference
        - -S1016   # Struct conversion - code clarity
        - -QF1007  # Merge conditional assignment - style preference
        - -QF1001  # De Morgan's law - style preference
        - -QF1011  # Omit type from declaration - style preference
        - -QF1012  # Use fmt.Fprintf instead of WriteString(fmt.Sprintf(...)) - style preference
        - -ST1023  # Omit type from declaration - style preference

    # Unused code
    unused:
      field-writes-are-uses: true
      exported-fields-are-used: false

    # Whitespace
    whitespace:
      multi-if: false
      multi-func: false


  # Exclusions configuration
  exclusions:
    # Mode of the generated files analysis
    # Options: strict, lax, disable
    generated: lax

    # Log a warning if an exclusion rule is unused
    warn-unused: true

    # Predefined exclusion rules
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy

    # Excluding configuration per-path, per-linter, per-text and per-source
    rules:
      # Exclude some linters from running on tests files
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - goconst
          - gocognit
          - unused

      # Exclude some staticcheck messages
      - linters:
          - staticcheck
        text: "SA9003:"

      # E2E test runner uses relaxed linting
      - path: cmd/e2e-runner/
        linters:
          - errcheck
          - gocognit
          - gocyclo
          - nestif
          - gocritic
          - godot
          - wrapcheck
          - gosec
          - revive
          - goprintffuncname
          - staticcheck

# Formatters configuration
formatters:
  # Enable specific formatters
  enable:
    - gofmt  # Format code with gofmt

# Issues configuration
issues:
  # Maximum issues count per one linter
  # Set to 0 to disable
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  # Set to 0 to disable
  max-same-issues: 0

  # Make issues output unique by line
  uniq-by-line: true

  # Show only new issues
  new: false

# Options for analysis running
run:
  # Timeout for analysis
  timeout: 5m

  # Include test files
  tests: true

  # Allow multiple parallel golangci-lint instances
  allow-parallel-runners: true

  # The mode used to evaluate relative paths
  relative-path-mode: gomod

# Severity settings
severity:
  # Set default severity
  default: error

  # Severity rules
  rules:
    - linters:
        - goconst
      severity: warning
