openapi: 3.1.0
info:
  title: Manual Channels API
  description: API endpoints for managing manual channels within manual stream sources
  version: 1.0.0

servers:
  - url: /api/v1
    description: API v1

paths:
  /sources/stream/{sourceId}/manual-channels:
    get:
      operationId: listManualChannels
      summary: List manual channels
      description: Returns all manual channel definitions for a manual stream source
      tags:
        - Manual Channels
      parameters:
        - $ref: '#/components/parameters/sourceId'
      responses:
        '200':
          description: List of manual channels
          content:
            application/json:
              schema:
                type: object
                required:
                  - items
                  - total
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/ManualChannel'
                  total:
                    type: integer
                    description: Total number of channels
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      operationId: replaceManualChannels
      summary: Replace all manual channels
      description: |
        Atomically replaces all manual channel definitions for a source.
        Triggers materialization to the channels table after successful update.
      tags:
        - Manual Channels
      parameters:
        - $ref: '#/components/parameters/sourceId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - channels
              properties:
                channels:
                  type: array
                  items:
                    $ref: '#/components/schemas/ManualChannelInput'
                  description: Complete list of channels (replaces all existing)
      responses:
        '200':
          description: Channels replaced successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - items
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/ManualChannel'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/ValidationError'

  /sources/stream/{sourceId}/manual-channels/import-m3u:
    post:
      operationId: importM3U
      summary: Import channels from M3U
      description: |
        Parse M3U content and optionally apply to the source.

        - With `apply=false`: Returns parsed channels for preview without persisting
        - With `apply=true`: Replaces all existing channels with parsed content
      tags:
        - Manual Channels
      parameters:
        - $ref: '#/components/parameters/sourceId'
        - name: apply
          in: query
          required: false
          schema:
            type: boolean
            default: false
          description: Whether to persist the imported channels
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              description: M3U playlist content
            example: |
              #EXTM3U
              #EXTINF:-1 tvg-id="bbc1" tvg-name="BBC One" tvg-logo="http://example.com/bbc1.png" group-title="UK",BBC One HD
              http://stream.example.com/bbc1.m3u8
              #EXTINF:-1 tvg-id="bbc2" tvg-name="BBC Two" group-title="UK",BBC Two HD
              http://stream.example.com/bbc2.m3u8
      responses:
        '200':
          description: M3U parsed (and optionally applied)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/M3UImportResult'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

  /sources/stream/{sourceId}/manual-channels/export.m3u:
    get:
      operationId: exportM3U
      summary: Export channels as M3U
      description: Generate M3U playlist from manual channel definitions
      tags:
        - Manual Channels
      parameters:
        - $ref: '#/components/parameters/sourceId'
      responses:
        '200':
          description: M3U playlist content
          content:
            text/plain:
              schema:
                type: string
              example: |
                #EXTM3U
                #EXTINF:-1 tvg-id="bbc1" tvg-name="BBC One" tvg-logo="http://example.com/bbc1.png" tvg-chno="1" group-title="UK",BBC One HD
                http://stream.example.com/bbc1.m3u8
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  parameters:
    sourceId:
      name: sourceId
      in: path
      required: true
      schema:
        type: string
        pattern: '^[0-9A-HJKMNP-TV-Z]{26}$'
      description: ULID of the manual stream source

  schemas:
    ManualChannel:
      type: object
      required:
        - id
        - source_id
        - channel_name
        - stream_url
        - enabled
        - priority
        - created_at
        - updated_at
      properties:
        id:
          type: string
          pattern: '^[0-9A-HJKMNP-TV-Z]{26}$'
          description: ULID of the channel
        source_id:
          type: string
          pattern: '^[0-9A-HJKMNP-TV-Z]{26}$'
          description: ULID of the parent stream source
        tvg_id:
          type: string
          maxLength: 255
          description: EPG ID for program matching
        tvg_name:
          type: string
          maxLength: 512
          description: Display name override
        tvg_logo:
          type: string
          maxLength: 2048
          description: Logo URL or @logo:token reference
        group_title:
          type: string
          maxLength: 255
          description: Category/group name
        channel_name:
          type: string
          minLength: 1
          maxLength: 512
          description: Required display name
        channel_number:
          type: integer
          minimum: 0
          description: Optional channel number
        stream_url:
          type: string
          minLength: 1
          maxLength: 4096
          description: Stream URL (http/https/rtsp)
        stream_type:
          type: string
          maxLength: 50
          description: Stream format hint
        language:
          type: string
          maxLength: 50
          description: Language code
        country:
          type: string
          maxLength: 10
          description: Country code
        is_adult:
          type: boolean
          description: Adult content flag
        enabled:
          type: boolean
          description: Whether channel is included in materialization
        priority:
          type: integer
          description: Sort order (higher = first)
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    ManualChannelInput:
      type: object
      required:
        - channel_name
        - stream_url
      properties:
        tvg_id:
          type: string
          maxLength: 255
        tvg_name:
          type: string
          maxLength: 512
        tvg_logo:
          type: string
          maxLength: 2048
        group_title:
          type: string
          maxLength: 255
        channel_name:
          type: string
          minLength: 1
          maxLength: 512
        channel_number:
          type: integer
          minimum: 0
        stream_url:
          type: string
          minLength: 1
          maxLength: 4096
          pattern: '^(https?|rtsp)://'
        stream_type:
          type: string
          maxLength: 50
        language:
          type: string
          maxLength: 50
        country:
          type: string
          maxLength: 10
        is_adult:
          type: boolean
          default: false
        enabled:
          type: boolean
          default: true
        priority:
          type: integer
          default: 0

    M3UImportResult:
      type: object
      required:
        - parsed_count
        - skipped_count
        - applied
        - channels
      properties:
        parsed_count:
          type: integer
          minimum: 0
          description: Number of channels successfully parsed
        skipped_count:
          type: integer
          minimum: 0
          description: Number of invalid entries skipped
        applied:
          type: boolean
          description: Whether changes were persisted to database
        channels:
          type: array
          items:
            $ref: '#/components/schemas/ManualChannel'
          description: Parsed channels (or persisted channels if applied=true)
        errors:
          type: array
          items:
            type: string
          description: Parse errors encountered

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
        details:
          type: string
          description: Additional error details

    ValidationError:
      type: object
      required:
        - error
        - fields
      properties:
        error:
          type: string
          description: Error summary
        fields:
          type: object
          additionalProperties:
            type: string
          description: Field-level validation errors

  responses:
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "operation only valid for manual sources"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "stream source not found"

    ValidationError:
      description: Validation failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'
          example:
            error: "validation failed"
            fields:
              "channels[0].stream_url": "must start with http, https, or rtsp"
              "channels[2].channel_name": "is required"
