// pkg/ffmpegd/proto/ffmpegd.proto
//
// tvarr-ffmpegd Protocol Buffer Service Definition
// This file defines the gRPC service for daemon-coordinator communication.
//
// Third-party clients can use this file to generate client code in any language.
// Install protoc and run:
//   protoc --go_out=. --go-grpc_out=. pkg/ffmpegd/proto/ffmpegd.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: pkg/ffmpegd/proto/ffmpegd.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FFmpegDaemon_Register_FullMethodName   = "/ffmpegd.FFmpegDaemon/Register"
	FFmpegDaemon_Heartbeat_FullMethodName  = "/ffmpegd.FFmpegDaemon/Heartbeat"
	FFmpegDaemon_Unregister_FullMethodName = "/ffmpegd.FFmpegDaemon/Unregister"
	FFmpegDaemon_Transcode_FullMethodName  = "/ffmpegd.FFmpegDaemon/Transcode"
	FFmpegDaemon_GetStats_FullMethodName   = "/ffmpegd.FFmpegDaemon/GetStats"
)

// FFmpegDaemonClient is the client API for FFmpegDaemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FFmpegDaemon is the gRPC service implemented by tvarr-ffmpegd workers.
// The coordinator connects to daemons to register, send heartbeats, and
// initiate transcoding jobs.
type FFmpegDaemonClient interface {
	// Register announces this daemon to the coordinator and reports capabilities.
	// Called once when daemon starts or reconnects.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Heartbeat sends periodic health updates with system stats.
	// Expected every 5 seconds. Coordinator marks daemon unhealthy after 30s.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Unregister gracefully removes daemon from the registry.
	// Called during graceful shutdown.
	Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error)
	// Transcode streams ES samples bidirectionally for transcoding.
	// Coordinator sends source samples, daemon returns transcoded samples.
	Transcode(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TranscodeMessage, TranscodeMessage], error)
	// GetStats returns current daemon statistics.
	// Used for dashboard and monitoring.
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
}

type fFmpegDaemonClient struct {
	cc grpc.ClientConnInterface
}

func NewFFmpegDaemonClient(cc grpc.ClientConnInterface) FFmpegDaemonClient {
	return &fFmpegDaemonClient{cc}
}

func (c *fFmpegDaemonClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, FFmpegDaemon_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fFmpegDaemonClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, FFmpegDaemon_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fFmpegDaemonClient) Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterResponse)
	err := c.cc.Invoke(ctx, FFmpegDaemon_Unregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fFmpegDaemonClient) Transcode(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TranscodeMessage, TranscodeMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FFmpegDaemon_ServiceDesc.Streams[0], FFmpegDaemon_Transcode_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TranscodeMessage, TranscodeMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FFmpegDaemon_TranscodeClient = grpc.BidiStreamingClient[TranscodeMessage, TranscodeMessage]

func (c *fFmpegDaemonClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, FFmpegDaemon_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FFmpegDaemonServer is the server API for FFmpegDaemon service.
// All implementations must embed UnimplementedFFmpegDaemonServer
// for forward compatibility.
//
// FFmpegDaemon is the gRPC service implemented by tvarr-ffmpegd workers.
// The coordinator connects to daemons to register, send heartbeats, and
// initiate transcoding jobs.
type FFmpegDaemonServer interface {
	// Register announces this daemon to the coordinator and reports capabilities.
	// Called once when daemon starts or reconnects.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Heartbeat sends periodic health updates with system stats.
	// Expected every 5 seconds. Coordinator marks daemon unhealthy after 30s.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Unregister gracefully removes daemon from the registry.
	// Called during graceful shutdown.
	Unregister(context.Context, *UnregisterRequest) (*UnregisterResponse, error)
	// Transcode streams ES samples bidirectionally for transcoding.
	// Coordinator sends source samples, daemon returns transcoded samples.
	Transcode(grpc.BidiStreamingServer[TranscodeMessage, TranscodeMessage]) error
	// GetStats returns current daemon statistics.
	// Used for dashboard and monitoring.
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	mustEmbedUnimplementedFFmpegDaemonServer()
}

// UnimplementedFFmpegDaemonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFFmpegDaemonServer struct{}

func (UnimplementedFFmpegDaemonServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedFFmpegDaemonServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedFFmpegDaemonServer) Unregister(context.Context, *UnregisterRequest) (*UnregisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unregister not implemented")
}
func (UnimplementedFFmpegDaemonServer) Transcode(grpc.BidiStreamingServer[TranscodeMessage, TranscodeMessage]) error {
	return status.Error(codes.Unimplemented, "method Transcode not implemented")
}
func (UnimplementedFFmpegDaemonServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedFFmpegDaemonServer) mustEmbedUnimplementedFFmpegDaemonServer() {}
func (UnimplementedFFmpegDaemonServer) testEmbeddedByValue()                      {}

// UnsafeFFmpegDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FFmpegDaemonServer will
// result in compilation errors.
type UnsafeFFmpegDaemonServer interface {
	mustEmbedUnimplementedFFmpegDaemonServer()
}

func RegisterFFmpegDaemonServer(s grpc.ServiceRegistrar, srv FFmpegDaemonServer) {
	// If the following call panics, it indicates UnimplementedFFmpegDaemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FFmpegDaemon_ServiceDesc, srv)
}

func _FFmpegDaemon_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFmpegDaemonServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFmpegDaemon_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFmpegDaemonServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FFmpegDaemon_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFmpegDaemonServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFmpegDaemon_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFmpegDaemonServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FFmpegDaemon_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFmpegDaemonServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFmpegDaemon_Unregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFmpegDaemonServer).Unregister(ctx, req.(*UnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FFmpegDaemon_Transcode_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FFmpegDaemonServer).Transcode(&grpc.GenericServerStream[TranscodeMessage, TranscodeMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FFmpegDaemon_TranscodeServer = grpc.BidiStreamingServer[TranscodeMessage, TranscodeMessage]

func _FFmpegDaemon_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFmpegDaemonServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFmpegDaemon_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFmpegDaemonServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FFmpegDaemon_ServiceDesc is the grpc.ServiceDesc for FFmpegDaemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FFmpegDaemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ffmpegd.FFmpegDaemon",
	HandlerType: (*FFmpegDaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _FFmpegDaemon_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _FFmpegDaemon_Heartbeat_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _FFmpegDaemon_Unregister_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _FFmpegDaemon_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transcode",
			Handler:       _FFmpegDaemon_Transcode_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/ffmpegd/proto/ffmpegd.proto",
}
