# Progress Events API Contract
# SSE endpoint: GET /api/v1/progress/events
# Content-Type: text/event-stream

openapi: 3.0.3
info:
  title: Progress Events API
  version: 2.0.0
  description: |
    Server-Sent Events (SSE) endpoint for real-time progress updates.
    Enhanced with structured error details and warning support.

paths:
  /api/v1/progress/events:
    get:
      summary: Subscribe to progress events
      description: |
        Establishes SSE connection for real-time progress updates.
        Events include progress, completed, error, cancelled, and heartbeat.
      responses:
        '200':
          description: SSE event stream
          content:
            text/event-stream:
              schema:
                $ref: '#/components/schemas/ProgressEvent'

components:
  schemas:
    ProgressEvent:
      type: object
      required:
        - event_type
        - progress
        - timestamp
      properties:
        event_type:
          type: string
          enum: [progress, completed, error, cancelled, heartbeat]
          description: Type of progress event
        progress:
          $ref: '#/components/schemas/UniversalProgress'
        timestamp:
          type: string
          format: date-time

    UniversalProgress:
      type: object
      required:
        - operation_id
        - operation_type
        - owner_id
        - owner_type
        - state
        - progress
        - started_at
        - updated_at
      properties:
        operation_id:
          type: string
          description: Unique identifier for this operation
        operation_type:
          type: string
          enum: [stream_ingestion, epg_ingestion, proxy_regeneration, pipeline]
          description: Type of operation
        owner_id:
          type: string
          format: ulid
          description: ULID of owning resource (proxy, source)
        owner_type:
          type: string
          description: Type of owner (stream_proxy, stream_source, epg_source)
        resource_id:
          type: string
          format: ulid
          nullable: true
          description: Optional additional resource ID
        state:
          type: string
          enum: [idle, preparing, connecting, downloading, processing, saving, cleanup, completed, error, cancelled]
        progress:
          type: number
          format: float
          minimum: 0
          maximum: 1
          description: Overall progress (0.0 to 1.0)
        message:
          type: string
          description: Current status message
        stages:
          type: array
          items:
            $ref: '#/components/schemas/StageInfo'
        current_stage_index:
          type: integer
          description: Index of currently executing stage
        started_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
          nullable: true
        error:
          type: string
          description: Simple error message (backward compatibility)
        error_detail:
          $ref: '#/components/schemas/ErrorDetail'
          nullable: true
          description: Structured error details (NEW)
        warning_count:
          type: integer
          description: Number of non-fatal warnings (NEW)
        warnings:
          type: array
          items:
            type: string
          description: Warning messages (NEW)
        metadata:
          type: object
          additionalProperties: true

    StageInfo:
      type: object
      required:
        - id
        - name
        - weight
        - state
        - progress
      properties:
        id:
          type: string
          description: Stage identifier
        name:
          type: string
          description: Human-readable stage name
        weight:
          type: number
          format: float
          description: Relative progress contribution (0.0 to 1.0)
        state:
          type: string
          enum: [idle, preparing, connecting, downloading, processing, saving, cleanup, completed, error, cancelled]
        progress:
          type: number
          format: float
          minimum: 0
          maximum: 1
        message:
          type: string
        current:
          type: integer
          description: Items processed
        total:
          type: integer
          description: Total items
        current_item:
          type: string
          description: Name of item being processed
        started_at:
          type: string
          format: date-time
          nullable: true
        completed_at:
          type: string
          format: date-time
          nullable: true

    ErrorDetail:
      type: object
      description: Structured error information for UI display (NEW)
      required:
        - stage
        - message
      properties:
        stage:
          type: string
          description: Stage that failed (e.g., "generate_m3u")
        message:
          type: string
          description: User-friendly error message
        technical:
          type: string
          description: Technical details for debugging
        suggestion:
          type: string
          description: Actionable suggestion for resolution

# Example SSE Event:
# event: progress
# data: {"event_type":"progress","progress":{"operation_id":"op-123","state":"processing","progress":0.5,"stages":[...],"error_detail":null},"timestamp":"2025-12-02T10:00:00Z"}
#
# event: error
# data: {"event_type":"error","progress":{"operation_id":"op-123","state":"error","error":"Pipeline failed","error_detail":{"stage":"generate_m3u","message":"Failed to write M3U file","technical":"permission denied: /output/proxy.m3u","suggestion":"Check output directory permissions"}},"timestamp":"2025-12-02T10:05:00Z"}
