# SSE Endpoints API Contract
# Feature: 001-003-sse-huma-refactor
# These endpoints should appear in OpenAPI after refactoring to Huma's sse.Register

openapi: 3.1.0
info:
  title: tvarr SSE Endpoints
  description: Server-Sent Events endpoints for real-time updates
  version: 1.0.0

paths:
  /api/v1/progress/events:
    get:
      operationId: progressEvents
      summary: Subscribe to progress events
      description: |
        Server-Sent Events stream for real-time progress updates.

        ## Connection Protocol
        - On connect: receives `:connected` comment
        - Every 30s without events: receives `:heartbeat <unix_epoch>` comment (Unix timestamp in seconds)

        ## Event Types
        - `progress`: Operation in progress (state: starting, running)
        - `completed`: Operation finished successfully (state: completed)
        - `error`: Operation failed (state: error)
        - `cancelled`: Operation was cancelled (state: cancelled)

        ## Usage Example
        ```javascript
        const eventSource = new EventSource('/api/v1/progress/events?owner_id=abc123');
        eventSource.addEventListener('progress', (e) => console.log(JSON.parse(e.data)));
        eventSource.addEventListener('completed', (e) => console.log(JSON.parse(e.data)));
        eventSource.addEventListener('error', (e) => console.log(JSON.parse(e.data)));
        ```
      tags:
        - Progress
      parameters:
        - name: operation_type
          in: query
          description: Filter events by operation type (e.g., stream_ingestion, epg_ingestion, proxy_generation)
          schema:
            type: string
        - name: owner_id
          in: query
          description: Filter events by owner ID (ULID of the source or proxy)
          schema:
            type: string
        - name: resource_id
          in: query
          description: Filter events by resource ID
          schema:
            type: string
      responses:
        '200':
          description: SSE event stream
          content:
            text/event-stream:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ProgressProgressEvent'
                  - $ref: '#/components/schemas/ProgressCompletedEvent'
                  - $ref: '#/components/schemas/ProgressErrorEvent'
                  - $ref: '#/components/schemas/ProgressCancelledEvent'

  /api/v1/logs/stream:
    get:
      operationId: logsStream
      summary: Subscribe to log events
      description: |
        Server-Sent Events stream for real-time log entries.

        ## Connection Protocol
        - On connect: receives `:connected` comment
        - On connect with `initial=N`: receives up to N recent log entries before live streaming
        - Every 30s without events: receives `:heartbeat <unix_epoch>` comment (Unix timestamp in seconds)

        ## Event Type
        - `log`: A log entry

        ## Usage Example
        ```javascript
        const eventSource = new EventSource('/api/v1/logs/stream?level=error&initial=100');
        eventSource.addEventListener('log', (e) => console.log(JSON.parse(e.data)));
        ```
      tags:
        - Logs
      parameters:
        - name: level
          in: query
          description: Filter by minimum log level
          schema:
            type: string
            enum: [trace, debug, info, warn, error]
        - name: module
          in: query
          description: Filter by module name
          schema:
            type: string
        - name: initial
          in: query
          description: Number of recent logs to send on connect (0-500)
          schema:
            type: integer
            minimum: 0
            maximum: 500
            default: 50
      responses:
        '200':
          description: SSE event stream
          content:
            text/event-stream:
              schema:
                $ref: '#/components/schemas/LogLogEvent'

components:
  schemas:
    ProgressProgressEvent:
      type: object
      description: Progress update event (event type: progress)
      allOf:
        - $ref: '#/components/schemas/ProgressResponse'

    ProgressCompletedEvent:
      type: object
      description: Operation completed event (event type: completed)
      allOf:
        - $ref: '#/components/schemas/ProgressResponse'

    ProgressErrorEvent:
      type: object
      description: Operation error event (event type: error)
      allOf:
        - $ref: '#/components/schemas/ProgressResponse'

    ProgressCancelledEvent:
      type: object
      description: Operation cancelled event (event type: cancelled)
      allOf:
        - $ref: '#/components/schemas/ProgressResponse'

    ProgressResponse:
      type: object
      description: Base progress operation schema
      required:
        - id
        - operation_name
        - operation_type
        - owner_id
        - owner_type
        - state
        - overall_percentage
        - current_stage
        - started_at
        - last_update
      properties:
        id:
          type: string
          description: Operation ID (ULID)
          example: "01HXYZ123456789ABCDEF"
        operation_name:
          type: string
          description: Human-readable operation name
          example: "Ingesting StreamCast News HD"
        operation_type:
          type: string
          description: Type of operation
          enum: [stream_ingestion, epg_ingestion, proxy_generation]
        owner_id:
          type: string
          description: ID of the resource that owns this operation (ULID)
          example: "01HXYZ987654321FEDCBA"
        owner_type:
          type: string
          description: Type of the owning resource
          example: "stream_source"
        state:
          type: string
          description: Current operation state
          enum: [starting, running, completed, error, cancelled]
        overall_percentage:
          type: number
          format: float
          minimum: 0
          maximum: 100
          description: Overall progress percentage (0-100)
          example: 45.5
        error:
          type: string
          description: Error message (present when state is error)
          example: "Connection timeout after 30s"
        stages:
          type: array
          description: List of operation stages
          items:
            $ref: '#/components/schemas/StageResponse'
        current_stage:
          type: string
          description: ID of the currently active stage
          example: "fetch"
        started_at:
          type: string
          format: date-time
          description: When the operation started
        last_update:
          type: string
          format: date-time
          description: When the operation was last updated
        completed_at:
          type: string
          format: date-time
          description: When the operation completed (null if still running)
        metadata:
          type: object
          additionalProperties: true
          description: Additional operation-specific metadata

    StageResponse:
      type: object
      description: Progress stage within an operation
      required:
        - id
        - name
        - state
        - percentage
      properties:
        id:
          type: string
          description: Stage identifier
          example: "fetch"
        name:
          type: string
          description: Human-readable stage name
          example: "Fetching M3U"
        state:
          type: string
          description: Stage state
          enum: [pending, in_progress, completed, skipped, error]
        percentage:
          type: number
          format: float
          minimum: 0
          maximum: 100
          description: Stage progress percentage (0-100)
          example: 100.0
        stage_step:
          type: string
          description: Current step within the stage
          example: "Downloaded 1024 of 2048 channels"

    LogLogEvent:
      type: object
      description: Log entry event (event type: log)
      allOf:
        - $ref: '#/components/schemas/LogEntryResponse'

    LogEntryResponse:
      type: object
      description: Log entry schema
      required:
        - id
        - timestamp
        - level
        - message
      properties:
        id:
          type: string
          description: Log entry ID (ULID)
          example: "01HXYZ123456789ABCDEF"
        timestamp:
          type: string
          format: date-time
          description: When the log entry was created
        level:
          type: string
          description: Log level
          enum: [trace, debug, info, warn, error]
        message:
          type: string
          description: Log message
          example: "Successfully ingested 1024 channels"
        module:
          type: string
          description: Module that generated the log
          example: "ingestor"
        target:
          type: string
          description: Target component
          example: "stream_source"
        file:
          type: string
          description: Source file name
          example: "ingestor.go"
        line:
          type: integer
          description: Source file line number
          example: 142
        fields:
          type: object
          additionalProperties: true
          description: Structured log fields
        context:
          type: object
          additionalProperties: true
          description: Request context (request_id, correlation_id, etc.)
