openapi: 3.1.0
info:
  title: Encoding Profiles API
  description: API for managing simplified encoding profiles in tvarr
  version: 1.0.0

servers:
  - url: /api/v1
    description: API v1

paths:
  /encoding-profiles:
    get:
      operationId: listEncodingProfiles
      summary: List all encoding profiles
      description: Returns a list of all encoding profiles, ordered by name
      tags:
        - Encoding Profiles
      parameters:
        - name: enabled
          in: query
          description: Filter by enabled status
          schema:
            type: boolean
        - name: is_system
          in: query
          description: Filter by system profile status
          schema:
            type: boolean
      responses:
        '200':
          description: List of encoding profiles
          content:
            application/json:
              schema:
                type: object
                properties:
                  profiles:
                    type: array
                    items:
                      $ref: '#/components/schemas/EncodingProfile'
                  count:
                    type: integer
                    description: Total number of profiles
        '500':
          $ref: '#/components/responses/InternalError'

    post:
      operationId: createEncodingProfile
      summary: Create a new encoding profile
      description: Creates a new encoding profile with the specified settings
      tags:
        - Encoding Profiles
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEncodingProfileRequest'
      responses:
        '201':
          description: Profile created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EncodingProfile'
        '400':
          $ref: '#/components/responses/ValidationError'
        '409':
          description: Profile with this name already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          $ref: '#/components/responses/InternalError'

  /encoding-profiles/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: Encoding profile ULID
        schema:
          type: string
          pattern: '^[0-9A-HJKMNP-TV-Z]{26}$'

    get:
      operationId: getEncodingProfile
      summary: Get an encoding profile by ID
      tags:
        - Encoding Profiles
      responses:
        '200':
          description: Encoding profile details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EncodingProfile'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

    put:
      operationId: updateEncodingProfile
      summary: Update an encoding profile
      description: Updates an existing encoding profile. System profiles can only have enabled toggled.
      tags:
        - Encoding Profiles
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEncodingProfileRequest'
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EncodingProfile'
        '400':
          $ref: '#/components/responses/ValidationError'
        '403':
          description: Cannot modify system profile (except enabled status)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          description: Profile name conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          $ref: '#/components/responses/InternalError'

    delete:
      operationId: deleteEncodingProfile
      summary: Delete an encoding profile
      description: Deletes an encoding profile. System profiles and profiles in use cannot be deleted.
      tags:
        - Encoding Profiles
      responses:
        '204':
          description: Profile deleted successfully
        '403':
          description: Cannot delete system profile or profile in use
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

  /encoding-profiles/{id}/set-default:
    parameters:
      - name: id
        in: path
        required: true
        description: Encoding profile ULID
        schema:
          type: string
          pattern: '^[0-9A-HJKMNP-TV-Z]{26}$'

    post:
      operationId: setDefaultEncodingProfile
      summary: Set a profile as the default
      description: Sets this profile as the default. Only one profile can be default at a time.
      tags:
        - Encoding Profiles
      responses:
        '200':
          description: Profile set as default
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EncodingProfile'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

  /encoding-profiles/quality-presets:
    get:
      operationId: listQualityPresets
      summary: List available quality presets
      description: Returns all quality presets with their FFmpeg parameter mappings
      tags:
        - Encoding Profiles
      responses:
        '200':
          description: List of quality presets
          content:
            application/json:
              schema:
                type: object
                properties:
                  presets:
                    type: array
                    items:
                      $ref: '#/components/schemas/QualityPresetInfo'

components:
  schemas:
    EncodingProfile:
      type: object
      required:
        - id
        - name
        - target_video_codec
        - target_audio_codec
        - quality_preset
        - hw_accel
        - is_default
        - is_system
        - enabled
        - created_at
        - updated_at
      properties:
        id:
          type: string
          description: ULID identifier
          pattern: '^[0-9A-HJKMNP-TV-Z]{26}$'
          example: "01ARZ3NDEKTSV4RRFFQ69G5FAV"
        name:
          type: string
          maxLength: 100
          description: Human-readable profile name
          example: "High Quality H.265"
        description:
          type: string
          maxLength: 500
          description: Profile description
          example: "High quality H.265 encoding for smart TVs"
        target_video_codec:
          $ref: '#/components/schemas/VideoCodec'
        target_audio_codec:
          $ref: '#/components/schemas/AudioCodec'
        quality_preset:
          $ref: '#/components/schemas/QualityPreset'
        hw_accel:
          $ref: '#/components/schemas/HWAccelType'
        is_default:
          type: boolean
          description: Whether this is the default profile
        is_system:
          type: boolean
          description: Whether this is a system-provided profile
        enabled:
          type: boolean
          description: Whether the profile can be used
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    CreateEncodingProfileRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          maxLength: 100
          minLength: 1
        description:
          type: string
          maxLength: 500
        target_video_codec:
          $ref: '#/components/schemas/VideoCodec'
          default: h264
        target_audio_codec:
          $ref: '#/components/schemas/AudioCodec'
          default: aac
        quality_preset:
          $ref: '#/components/schemas/QualityPreset'
          default: medium
        hw_accel:
          $ref: '#/components/schemas/HWAccelType'
          default: auto
        enabled:
          type: boolean
          default: true

    UpdateEncodingProfileRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
          minLength: 1
        description:
          type: string
          maxLength: 500
        target_video_codec:
          $ref: '#/components/schemas/VideoCodec'
        target_audio_codec:
          $ref: '#/components/schemas/AudioCodec'
        quality_preset:
          $ref: '#/components/schemas/QualityPreset'
        hw_accel:
          $ref: '#/components/schemas/HWAccelType'
        enabled:
          type: boolean

    VideoCodec:
      type: string
      enum:
        - h264
        - h265
        - vp9
        - av1
      description: Target video codec

    AudioCodec:
      type: string
      enum:
        - aac
        - opus
        - ac3
        - eac3
        - mp3
      description: Target audio codec

    QualityPreset:
      type: string
      enum:
        - low
        - medium
        - high
        - ultra
      description: Quality level preset

    HWAccelType:
      type: string
      enum:
        - auto
        - none
        - cuda
        - vaapi
        - qsv
        - videotoolbox
      description: Hardware acceleration type

    QualityPresetInfo:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/QualityPreset'
        description:
          type: string
          example: "Medium quality, balanced bitrate and quality"
        video_crf:
          type: integer
          description: CRF value for video encoding
          example: 23
        video_maxrate:
          type: string
          description: Maximum video bitrate
          example: "5M"
        audio_bitrate:
          type: string
          description: Audio bitrate
          example: "192k"

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          additionalProperties: true
          description: Additional error details

  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "not_found"
            message: "Encoding profile not found"

    ValidationError:
      description: Validation error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "validation_error"
            message: "Invalid request"
            details:
              name: "Name is required"

    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "internal_error"
            message: "An internal error occurred"

tags:
  - name: Encoding Profiles
    description: Manage encoding profiles for relay transcoding
